INSERT INTO categorias (nombre_categoria) VALUES
('Cola'),
('Naranja'),
('Limon'),
('Agua saborizada'),
('Energetica'),
('Te helado'),
('Isotonica'),
('Uva'),
('Manzana'),
('Tropical'),
('Toronja'),
('Ginger Ale'),
('Soda'),
('Agua mineral'),
('Cafe frio');